variables:
  TF_HTTP_USERNAME: $GIT_USER_EMAIL
  TF_HTTP_PASSWORD: $GITLAB_CI_TOKEN
image: 
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
stages:
  - validate
  - deploy
before_script:
  - rm -rf .terraform
validate:
  stage: validate
  before_script:
   - |
    set -o allexport
    echo 'set variable for dev env'
    source 	$env_dev
    set +o allexport
    export GOOGLE_PROJECT=$GCP_PROJECT_ID
  script:
    - cd infra
    - terraform init -backend-config=backend.dev.conf
    - terraform validate
    - terraform plan -var-file dev.tfvars -var-file version.tfvars.json
  only:
    - merge_requests  
    
apply-dev:
  before_script:
   - |
    set -o allexport
    echo 'set variable for dev env'
    source 	$env_dev
    set +o allexport
    export GOOGLE_PROJECT=$GCP_PROJECT_ID
  stage: deploy
  script:
    - cd infra
    - terraform init -backend-config=backend.dev.conf
    - terraform plan -var-file dev.tfvars -var-file version.tfvars.json -out plan.cache
    - terraform apply -auto-approve plan.cache
  only:
    - release/test
